before_install:
  - gem install bundler

cache: bundler

notifications:
  email: false

rvm:
 - 2.3.1
 - ruby-head

gemfile:
  - Gemfile
  - gemfiles/rails-4-1-stable.gemfile
  - gemfiles/rails-master.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - "mysql -e 'create database carrierwave_test;'"
